### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tolomea** [adamchainz/pytest-randomly#92]
When running with deprecation warnings on I encountered this

pytest_randomly.py:67: DeprecationWarning: `factory.fuzzy.set_random_state` is deprecated. You should use `factory.random.set_random_state` instead
    factory_set_random_state(random_states[seed])

**Comment by adamchainz** [comment]
version 1.2.3 out with fix

**Comment by tolomea** [comment]
thank you
